version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: contactlist_app
    container_name: contactlist_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=contactlist
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: contactlist_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: contactlist
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
